# fly.toml app configuration file generated for dancastillo-dev-api on 2024-11-26T23:33:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dancastillo-dev-api'
primary_region = 'mia'

[build]

[env]
  PORT = 3000
  HOST = "127.0.0.1"

[[services]]
  internal_port = 5432 # Postgres instance
  protocol = "tcp"

[[services.ports]]
  handlers = ["pg_tls"]
  port = 5432

# TODO-DAN: figure out how to run migrations
# [deploy]
#   release_command = "npm run db:apply:changes"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
