name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  ci:
    uses: dancastillo/workflows/.github/workflows/ts-ci.yml@main
    with:
      license-check: true
      test: false
