name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  ci:
    uses: dancastillo/workflows/.github/workflows/ts-ci.yml@main
    with:
      license-check: true
      test: false

  test:
    uses: dancastillo/workflows/.github/workflows/test-with-postgres.yml@main
    with:
      db-migrations: true
      db-seed: true
