name: Test with PostgreSQL

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: maindb

    strategy:
      matrix:
        node-version: [lts/*]
        os: [ubuntu-latest]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run DB migrations
        run: npm run db:migrate 
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/maindb"

      - name: Run DB seeds
        run: npm run db:seed 
        env: 
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/maindb"

      - name: Run tests
        run: npm run test
        env: 
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/maindb"
